<?php

function dfp_map_help( $path, $arg ) {
	switch( $path )
	{
		case 'admin/help#dino_friendly_places':
			return '<p>' . t("Maps dinosaur friendly places created by users") . '</p>';
			break;
	}	
}

function dfp_map_node_view( $node )
{
    if( $node->type == 'dino_friendly_places_map' )
    {
        
		drupal_add_js('http://maps.google.com/maps/api/js?sensor=false', 'external');
		$points = "";
		$sql = "SELECT
				n.nid, v.title, lat.dfp_venue_latitude_value as latitude, lon.dfp_venue_longitude_value as longitude
				FROM node n LEFT JOIN node_revision v ON ( n.vid=v.vid ) 
				LEFT JOIN field_revision_body b ON ( n.vid=b.revision_id )
				LEFT JOIN field_revision_dfp_venue_latitude lat ON ( n.vid=lat.revision_id ) 
				LEFT JOIN field_revision_dfp_venue_longitude lon ON ( n.vid=lon.revision_id ) 
				WHERE n.type='dino_friendly_places_venue' ";
		$result = db_query( $sql );
		foreach( $result as $row )
		{
			$points .= "
			
			var location = new google.maps.LatLng( {$row->latitude}, {$row->longitude} );
			var marker = new google.maps.Marker({position: location, map: map });
			var infowindow = new google.maps.InfoWindow({ content: \"<strong><a href='node/{$row->nid}'>{$row->title}</a></strong>\"  });
		  	google.maps.event.addListener(marker, 'click', function() {
		    	infowindow.open(map,marker);
		  	});
			";
		}
	
			$longitude = $node->dfp_map_longitude['und'][0]['value'];
		$latitude = $node->dfp_map_latitude['und'][0]['value'];
		$zoom = $node->dfp_map_zoom['und'][0]['value'];
		
		$js = "
		function initialize() {
		    var latlng = new google.maps.LatLng({$latitude}, {$longitude});
		    var myOptions = {
		      zoom: {$zoom},
		      center: latlng,
		      mapTypeId: google.maps.MapTypeId.ROADMAP
		    };
		    var map = new google.maps.Map(document.getElementById('map_canvas'), myOptions);
		    " . $points . "
	  	}
	  	
	  	jQuery(document).ready(function () { initialize(); });
	  	
	  	";
		
		drupal_add_js( $js , 'inline');
	}
}